#!/usr/bin/env bash
# Freeze SHA-256 hashes for protocol/* normative specs, the Python reference and
# the shared-vectors/rvn1 fixtures (external review packet).
#
# Usage:
#   bash scripts/freeze_protocol_hashes.sh           # regenerate the committed manifest
#   bash scripts/freeze_protocol_hashes.sh OUT.md    # write the manifest elsewhere
#   bash scripts/freeze_protocol_hashes.sh --check   # CI: exit 1 if any file drifted
#
# The manifest is a pure function of the tree (no timestamp / branch / commit
# header), so `--check` is a byte diff. A frozen file that changes, appears or
# disappears fails CI until the manifest is regenerated in the same change —
# which forces the change to be deliberate and reviewed. A change to a frozen
# wire format must additionally be versioned (protocol/PROTOCOL_VERSIONS.md).
set -euo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"
MANIFEST="$REPO/docs/PROTOCOL_FREEZE_HASHES_V1.md"

sha256_of() {
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1"
  else
    sha256sum "$1"
  fi
}

generate() {
  echo "# Raven protocol freeze hashes"
  echo "#"
  echo "# Generated by scripts/freeze_protocol_hashes.sh — do not edit by hand."
  echo "# CI runs \`bash scripts/freeze_protocol_hashes.sh --check\`: any listed file"
  echo "# that changes, and any new/removed file under the covered paths, fails CI"
  echo "# until this manifest is regenerated in the same change. Wire-format changes"
  echo "# must also be versioned in protocol/PROTOCOL_VERSIONS.md."
  echo "#"
  echo "# Format: SHA256  path (relative to repo root)"
  echo
  cd "$REPO"
  # Normative markdown + reference python / fixtures under protocol/
  find protocol -type f \( -name '*.md' -o -name '*.py' -o -name '*.json' -o -name '*.toml' -o -name '*.txt' -o -name '*.ini' \) \
    ! -path '*/__pycache__/*' ! -path '*/.pytest_cache/*' \
    | LC_ALL=C sort \
    | while read -r f; do
        sha256_of "$f"
      done
  echo
  echo "# Shared vectors (rvn1) — byte-exact fixtures"
  find shared-vectors/rvn1 -type f \( -name '*.json' -o -name '*.md' \) \
    ! -path '*/__pycache__/*' \
    | LC_ALL=C sort \
    | while read -r f; do
        sha256_of "$f"
      done
}

if [[ "${1:-}" == "--check" ]]; then
  TMP="$(mktemp)"
  trap 'rm -f "$TMP"' EXIT
  generate >"$TMP"
  if ! diff -u "$MANIFEST" "$TMP"; then
    echo >&2
    echo "PROTOCOL_FREEZE_DRIFT: frozen protocol / reference / rvn1 vector files differ" >&2
    echo "from docs/PROTOCOL_FREEZE_HASHES_V1.md (diff above: - committed, + tree)." >&2
    echo "If the change is intentional and versioned, regenerate the manifest with" >&2
    echo "  bash scripts/freeze_protocol_hashes.sh" >&2
    echo "and commit it together with the change." >&2
    exit 1
  fi
  echo "protocol freeze hashes OK ($(grep -cE '^[0-9a-f]{64}  ' "$MANIFEST") files)"
  exit 0
fi

OUT="${1:-$MANIFEST}"
generate >"$OUT"
echo "wrote $OUT"
wc -l "$OUT"
