//! Rust consumer for the shared-vector cases added for the post-freeze strict
//! decoder rules (`negative/envelope_*_001`, `envelope_expired_002`), the full
//! prekey-bundle signing KATs (`prekey/bundle_signing_00{1,2}`,
//! `negative/prekey_bad_sig_002`) and the PairInit V1 structural negatives
//! (`atsam/negative/pair_init_v1_*`), plus the 2026-10-07 negatives: the
//! Ed25519 weak-key forgery (`negative/ed25519_weak_key_forgery_001`), the
//! re-signed small-order PairInit ephemeral
//! (`atsam/negative/pair_init_v1_small_order_ephemeral_001`) and the PairInit /
//! PairResponse clock-skew boundaries (`atsam/pair_init_v1_clock_skew_001`).
//! Generated by `protocol/reference/generate_rvn1.py`, which asserts the Python
//! reference rejects / accepts the same bytes.

use std::path::{Path, PathBuf};

use raven_core::bridge::{decide, BridgeAction, BridgeRole, DropReason};
use raven_core::device_cert::DeviceCertificate;
use raven_core::envelope::Envelope;
use raven_core::identity::Identity;
use raven_core::pair_init::{
    decode_init, decode_response, verify_init, verify_response, PairInitTrust,
};
use raven_core::prekey_bundle::PrekeyBundle;
use serde_json::Value;

fn rvn1() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../shared-vectors/rvn1")
}

fn load(rel: &str) -> Value {
    let p = rvn1().join(rel);
    let raw = std::fs::read(&p).unwrap_or_else(|e| panic!("missing vector {}: {e}", p.display()));
    serde_json::from_slice(&raw).expect("vector json")
}

fn hex_field(v: &Value, key: &str) -> Vec<u8> {
    hex::decode(v[key].as_str().unwrap_or_else(|| panic!("{key} missing"))).expect("hex")
}

fn arr32(b: &[u8]) -> [u8; 32] {
    b.try_into().expect("32 bytes")
}

#[test]
fn strict_envelope_negatives_reject() {
    let dir = rvn1().join("negative");
    let mut seen = 0;
    let mut names: Vec<_> = std::fs::read_dir(&dir)
        .expect("negative dir")
        .map(|e| e.expect("entry").file_name().into_string().expect("utf8"))
        .filter(|n| n.starts_with("envelope_") && n.ends_with("_001.json"))
        .collect();
    names.sort();
    for name in names {
        let v = load(&format!("negative/{name}"));
        if v["expected"]["unpack_result"] != "reject" {
            continue;
        }
        let packed = hex_field(&v["inputs"], "packed_hex");
        assert!(
            Envelope::unpack(&packed).is_none(),
            "{name}: strict decoder accepted a shared negative"
        );
        seen += 1;
    }
    // bad_version, auth_len_63, reserved_flag, env_type_0/5, expires_not_after_created,
    // trailing_byte, truncated.
    assert!(
        seen >= 8,
        "expected the strict envelope negatives, saw {seen}"
    );
}

#[test]
fn expired_envelope_decodes_but_relay_drops() {
    let v = load("negative/envelope_expired_002.json");
    let packed = hex_field(&v["inputs"], "packed_hex");
    let clock = v["inputs"]["validation_clock_ms"].as_u64().expect("clock");
    let env = Envelope::unpack(&packed).expect("well-formed expired envelope must decode");
    assert!(env.expires_at < clock);
    assert_eq!(
        decide(&packed, BridgeRole::Relay, clock, false),
        BridgeAction::Drop {
            reason: DropReason::Expired
        }
    );
}

fn bundle_from_inputs(inp: &Value) -> PrekeyBundle {
    PrekeyBundle {
        identity_ed25519_pub: arr32(&hex_field(inp, "identity_ed25519_pub_hex")),
        device_id: inp["device_id"].as_str().expect("device_id").to_string(),
        x25519_pub: arr32(&hex_field(inp, "x25519_pub_hex")),
        mlkem768_ek: hex_field(inp, "mlkem768_ek_hex"),
        signed_prekey_id: inp["signed_prekey_id"].as_u64().expect("spk id") as u32,
        one_time_prekey_id: inp["one_time_prekey_id"].as_u64().expect("otp id") as u32,
        one_time_x25519_pub: inp["one_time_x25519_pub_hex"]
            .as_str()
            .map(|h| arr32(&hex::decode(h).expect("otp hex"))),
        created_at_ms: inp["created_at_ms"].as_u64().expect("created"),
        expires_at_ms: inp["expires_at_ms"].as_u64().expect("expires"),
        signature: [0u8; 64],
    }
}

#[test]
fn prekey_bundle_signing_kats_match_rust() {
    for case in ["bundle_signing_001", "bundle_signing_002"] {
        let v = load(&format!("prekey/{case}.json"));
        let mut b = bundle_from_inputs(&v["inputs"]);
        let exp = &v["expected"];
        assert_eq!(
            b.signing_bytes().expect("signing bytes"),
            hex_field(exp, "signing_bytes_hex"),
            "{case}: signing bytes diverge from the Python reference"
        );
        b.signature = hex_field(exp, "signature_hex")
            .try_into()
            .expect("64-byte sig");
        b.verify(b.created_at_ms)
            .unwrap_or_else(|e| panic!("{case}: {e}"));
        for c in exp["clock_cases"].as_array().expect("clock cases") {
            let now = c["now_ms"].as_u64().expect("now");
            match c["result"].as_str().expect("result") {
                "accept" => b
                    .verify(now)
                    .unwrap_or_else(|e| panic!("{case} at {now}: {e}")),
                _ => assert_eq!(
                    b.verify(now).unwrap_err(),
                    c["error"].as_str().expect("error"),
                    "{case} at {now}"
                ),
            }
        }
    }
}

#[test]
fn prekey_bad_sig_002_rejects() {
    let v = load("negative/prekey_bad_sig_002.json");
    let good = load("prekey/bundle_signing_001.json");
    let mut b = bundle_from_inputs(&good["inputs"]);
    let inp = &v["inputs"];
    assert_eq!(
        b.signing_bytes().expect("signing bytes"),
        hex_field(inp, "signing_bytes_hex")
    );
    b.signature = hex_field(inp, "signature_hex")
        .try_into()
        .expect("64-byte sig");
    let clock = inp["validation_clock_ms"].as_u64().expect("clock");
    assert_eq!(
        b.verify(clock).unwrap_err(),
        v["expected"]["error"].as_str().expect("error")
    );
}

#[test]
fn pair_init_v1_structural_negatives_reject() {
    let dir = rvn1().join("atsam/negative");
    let mut names: Vec<_> = std::fs::read_dir(&dir)
        .expect("atsam negative dir")
        .map(|e| e.expect("entry").file_name().into_string().expect("utf8"))
        .filter(|n| n.starts_with("pair_init_v1_") && n.ends_with(".json"))
        .filter(|n| !n.starts_with("pair_init_v1_as_v2"))
        .collect();
    names.sort();
    // 7 decode-structure cases + the re-signed small-order ephemeral.
    assert!(names.len() >= 8, "PairInit V1 negatives missing: {names:?}");
    for name in names {
        let v = load(&format!("atsam/negative/{name}"));
        let wire = hex_field(&v["input"], "pair_init_wire_hex");
        let err = decode_init(&wire).expect_err(&name);
        assert_eq!(
            format!("{err:?}"),
            v["expected"]["rust_error"].as_str().expect("rust_error"),
            "{name}"
        );
    }
}

fn arr64(b: &[u8]) -> [u8; 64] {
    b.try_into().expect("64 bytes")
}

#[test]
fn ed25519_weak_key_forgery_rejected() {
    let v = load("negative/ed25519_weak_key_forgery_001.json");
    let inp = &v["inputs"];
    let public = arr32(&hex_field(inp, "public_key_hex"));
    let signature = arr64(&hex_field(inp, "signature_hex"));
    let mut identity = [0u8; 32];
    identity[0] = 1;
    assert_eq!(public, identity, "A must be the identity encoding");
    assert_eq!(
        &signature[..32],
        &identity,
        "R must be the identity encoding"
    );
    assert_eq!(&signature[32..], &[0u8; 32], "s must be zero");
    assert_eq!(v["expected"]["verify_result"], "reject");
    let messages = inp["messages_hex"].as_array().expect("messages");
    assert!(messages.len() >= 3);
    for m in messages {
        let msg = hex::decode(m.as_str().expect("hex")).expect("hex");
        assert!(
            !Identity::verify(&public, &msg, &signature),
            "weak-key forgery accepted for message {m}"
        );
    }
    let packed = hex_field(inp, "envelope_packed_hex");
    let env = Envelope::unpack(&packed).expect("forged envelope is structurally valid");
    assert_eq!(env.sender_authentication.to_vec(), signature.to_vec());
    assert!(!env.verify(&public), "envelope verify accepted the forgery");
    let blocklist = inp["small_order_encodings_hex"]
        .as_array()
        .expect("blocklist");
    assert_eq!(blocklist.len(), 7);
    for e in blocklist {
        let entry = arr32(&hex::decode(e.as_str().expect("hex")).expect("hex"));
        for sign in [0x00u8, 0x80] {
            let mut point = entry;
            point[31] |= sign;
            let mut sig = [0u8; 64];
            sig[..32].copy_from_slice(&point);
            for m in messages {
                let msg = hex::decode(m.as_str().expect("hex")).expect("hex");
                assert!(
                    !Identity::verify(&point, &msg, &sig),
                    "small-order A = R = {} accepted",
                    hex::encode(point)
                );
            }
        }
    }
}

#[test]
fn pair_init_v1_small_order_ephemeral_is_signed_but_rejected() {
    let v = load("atsam/negative/pair_init_v1_small_order_ephemeral_001.json");
    let inp = &v["input"];
    let wire = hex_field(inp, "pair_init_wire_hex");
    let offset = inp["initiator_ephemeral_offset"].as_u64().expect("offset") as usize;
    assert_eq!(
        wire[offset..offset + 32].to_vec(),
        hex_field(inp, "initiator_ephemeral_x25519_pub_hex")
    );
    // Only the structural rule fails: the initiator signature is genuine.
    let mut signing = b"rvn1/pair-init".to_vec();
    signing.extend_from_slice(&wire[..wire.len() - 64]);
    assert_eq!(v["expected"]["initiator_signature_valid"], true);
    assert!(Identity::verify(
        &arr32(&hex_field(inp, "initiator_device_ed_pub_hex")),
        &signing,
        &arr64(&wire[wire.len() - 64..]),
    ));
    let err = decode_init(&wire).expect_err("small-order ephemeral must be rejected");
    assert_eq!(
        format!("{err:?}"),
        v["expected"]["rust_error"].as_str().expect("rust_error")
    );
}

fn cert_from(fields: &Value) -> DeviceCertificate {
    DeviceCertificate {
        device_ed_pub: arr32(&hex_field(fields, "device_ed_pub_hex")),
        device_x_pub: arr32(&hex_field(fields, "device_x_pub_hex")),
        device_id: fields["device_id"].as_str().expect("device_id").to_string(),
        not_before_ms: fields["not_before_ms"].as_u64().expect("not_before"),
        not_after_ms: fields["not_after_ms"].as_u64().expect("not_after"),
        capabilities: fields["capabilities"].as_u64().expect("capabilities"),
        signature: arr64(&hex_field(fields, "signature_hex")),
        user_ed_pub: arr32(&hex_field(fields, "user_ed_pub_hex")),
    }
}

fn outcome<E: std::fmt::Debug>(result: Result<(), E>) -> (String, Option<String>) {
    match result {
        Ok(()) => ("accept".into(), None),
        Err(e) => ("reject".into(), Some(format!("{e:?}"))),
    }
}

#[test]
fn pair_init_v1_clock_skew_boundaries() {
    let v = load("atsam/pair_init_v1_clock_skew_001.json");
    let inp = &v["input"];
    assert_eq!(
        inp["max_peer_clock_skew_ms"].as_u64(),
        Some(raven_core::prekey_lifecycle::MAX_PREKEY_FUTURE_SKEW_MS)
    );
    let alice = cert_from(&inp["initiator_device_cert"]);
    let bob = cert_from(&inp["responder_device_cert"]);
    let ek = hex_field(inp, "responder_mlkem768_ek_hex");
    let mut seen = (0, 0);
    for case in v["expected"]["init_cases"].as_array().expect("init cases") {
        let label = case["label"].as_str().expect("label");
        let init = decode_init(&hex_field(case, "pair_init_wire_hex")).expect(label);
        let pk = &case["responder_prekey"];
        let prekey = PrekeyBundle {
            identity_ed25519_pub: arr32(&hex_field(pk, "identity_ed25519_pub_hex")),
            device_id: pk["device_id"].as_str().expect("device_id").to_string(),
            x25519_pub: arr32(&hex_field(pk, "x25519_pub_hex")),
            mlkem768_ek: ek.clone(),
            signed_prekey_id: pk["signed_prekey_id"].as_u64().expect("spk") as u32,
            one_time_prekey_id: pk["one_time_prekey_id"].as_u64().expect("otp") as u32,
            one_time_x25519_pub: Some(arr32(&hex_field(pk, "one_time_x25519_pub_hex"))),
            created_at_ms: pk["created_at_ms"].as_u64().expect("created"),
            expires_at_ms: pk["expires_at_ms"].as_u64().expect("expires"),
            signature: arr64(&hex_field(pk, "signature_hex")),
        };
        let trust = PairInitTrust {
            initiator_certificate: &alice,
            responder_certificate: &bob,
            responder_prekey: &prekey,
            initiator_revoked: false,
            responder_revoked: false,
        };
        let now = case["now_ms"].as_u64().expect("now");
        let (result, error) = outcome(verify_init(&init, &trust, now));
        assert_eq!(result, case["result"].as_str().expect("result"), "{label}");
        assert_eq!(error.as_deref(), case["rust_error"].as_str(), "{label}");
        if result == "accept" {
            seen.0 += 1;
        } else {
            seen.1 += 1;
        }
    }
    assert_eq!(seen, (3, 3), "accept/reject case counts");

    let source = load("atsam/pair_init_v1_001.json");
    let init = decode_init(&hex_field(&source["expected"], "pair_init_wire_hex")).expect("init");
    let response = decode_response(&hex_field(inp, "pair_response_wire_hex")).expect("response");
    let root = arr32(&hex_field(inp, "provisional_k_root_hex"));
    let cases = v["expected"]["response_cases"]
        .as_array()
        .expect("response cases");
    assert_eq!(cases.len(), 4);
    for case in cases {
        let label = case["label"].as_str().expect("label");
        let now = case["now_ms"].as_u64().expect("now");
        let (result, error) = outcome(verify_response(&response, &init, &root, now));
        assert_eq!(result, case["result"].as_str().expect("result"), "{label}");
        assert_eq!(error.as_deref(), case["rust_error"].as_str(), "{label}");
    }
}
