//! Rust consumer for the shared-vector cases added for the post-freeze strict
//! decoder rules (`negative/envelope_*_001`, `envelope_expired_002`), the full
//! prekey-bundle signing KATs (`prekey/bundle_signing_00{1,2}`,
//! `negative/prekey_bad_sig_002`) and the PairInit V1 structural negatives
//! (`atsam/negative/pair_init_v1_*`). Generated by
//! `protocol/reference/generate_rvn1.py`, which asserts the Python reference
//! rejects / accepts the same bytes.

use std::path::{Path, PathBuf};

use raven_core::bridge::{decide, BridgeAction, BridgeRole, DropReason};
use raven_core::envelope::Envelope;
use raven_core::pair_init::decode_init;
use raven_core::prekey_bundle::PrekeyBundle;
use serde_json::Value;

fn rvn1() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../shared-vectors/rvn1")
}

fn load(rel: &str) -> Value {
    let p = rvn1().join(rel);
    let raw = std::fs::read(&p).unwrap_or_else(|e| panic!("missing vector {}: {e}", p.display()));
    serde_json::from_slice(&raw).expect("vector json")
}

fn hex_field(v: &Value, key: &str) -> Vec<u8> {
    hex::decode(v[key].as_str().unwrap_or_else(|| panic!("{key} missing"))).expect("hex")
}

fn arr32(b: &[u8]) -> [u8; 32] {
    b.try_into().expect("32 bytes")
}

#[test]
fn strict_envelope_negatives_reject() {
    let dir = rvn1().join("negative");
    let mut seen = 0;
    let mut names: Vec<_> = std::fs::read_dir(&dir)
        .expect("negative dir")
        .map(|e| e.expect("entry").file_name().into_string().expect("utf8"))
        .filter(|n| n.starts_with("envelope_") && n.ends_with("_001.json"))
        .collect();
    names.sort();
    for name in names {
        let v = load(&format!("negative/{name}"));
        if v["expected"]["unpack_result"] != "reject" {
            continue;
        }
        let packed = hex_field(&v["inputs"], "packed_hex");
        assert!(
            Envelope::unpack(&packed).is_none(),
            "{name}: strict decoder accepted a shared negative"
        );
        seen += 1;
    }
    // bad_version, auth_len_63, reserved_flag, env_type_0/5, expires_not_after_created,
    // trailing_byte, truncated.
    assert!(
        seen >= 8,
        "expected the strict envelope negatives, saw {seen}"
    );
}

#[test]
fn expired_envelope_decodes_but_relay_drops() {
    let v = load("negative/envelope_expired_002.json");
    let packed = hex_field(&v["inputs"], "packed_hex");
    let clock = v["inputs"]["validation_clock_ms"].as_u64().expect("clock");
    let env = Envelope::unpack(&packed).expect("well-formed expired envelope must decode");
    assert!(env.expires_at < clock);
    assert_eq!(
        decide(&packed, BridgeRole::Relay, clock, false),
        BridgeAction::Drop {
            reason: DropReason::Expired
        }
    );
}

fn bundle_from_inputs(inp: &Value) -> PrekeyBundle {
    PrekeyBundle {
        identity_ed25519_pub: arr32(&hex_field(inp, "identity_ed25519_pub_hex")),
        device_id: inp["device_id"].as_str().expect("device_id").to_string(),
        x25519_pub: arr32(&hex_field(inp, "x25519_pub_hex")),
        mlkem768_ek: hex_field(inp, "mlkem768_ek_hex"),
        signed_prekey_id: inp["signed_prekey_id"].as_u64().expect("spk id") as u32,
        one_time_prekey_id: inp["one_time_prekey_id"].as_u64().expect("otp id") as u32,
        one_time_x25519_pub: inp["one_time_x25519_pub_hex"]
            .as_str()
            .map(|h| arr32(&hex::decode(h).expect("otp hex"))),
        created_at_ms: inp["created_at_ms"].as_u64().expect("created"),
        expires_at_ms: inp["expires_at_ms"].as_u64().expect("expires"),
        signature: [0u8; 64],
    }
}

#[test]
fn prekey_bundle_signing_kats_match_rust() {
    for case in ["bundle_signing_001", "bundle_signing_002"] {
        let v = load(&format!("prekey/{case}.json"));
        let mut b = bundle_from_inputs(&v["inputs"]);
        let exp = &v["expected"];
        assert_eq!(
            b.signing_bytes().expect("signing bytes"),
            hex_field(exp, "signing_bytes_hex"),
            "{case}: signing bytes diverge from the Python reference"
        );
        b.signature = hex_field(exp, "signature_hex")
            .try_into()
            .expect("64-byte sig");
        b.verify(b.created_at_ms)
            .unwrap_or_else(|e| panic!("{case}: {e}"));
        for c in exp["clock_cases"].as_array().expect("clock cases") {
            let now = c["now_ms"].as_u64().expect("now");
            match c["result"].as_str().expect("result") {
                "accept" => b
                    .verify(now)
                    .unwrap_or_else(|e| panic!("{case} at {now}: {e}")),
                _ => assert_eq!(
                    b.verify(now).unwrap_err(),
                    c["error"].as_str().expect("error"),
                    "{case} at {now}"
                ),
            }
        }
    }
}

#[test]
fn prekey_bad_sig_002_rejects() {
    let v = load("negative/prekey_bad_sig_002.json");
    let good = load("prekey/bundle_signing_001.json");
    let mut b = bundle_from_inputs(&good["inputs"]);
    let inp = &v["inputs"];
    assert_eq!(
        b.signing_bytes().expect("signing bytes"),
        hex_field(inp, "signing_bytes_hex")
    );
    b.signature = hex_field(inp, "signature_hex")
        .try_into()
        .expect("64-byte sig");
    let clock = inp["validation_clock_ms"].as_u64().expect("clock");
    assert_eq!(
        b.verify(clock).unwrap_err(),
        v["expected"]["error"].as_str().expect("error")
    );
}

#[test]
fn pair_init_v1_structural_negatives_reject() {
    let dir = rvn1().join("atsam/negative");
    let mut names: Vec<_> = std::fs::read_dir(&dir)
        .expect("atsam negative dir")
        .map(|e| e.expect("entry").file_name().into_string().expect("utf8"))
        .filter(|n| n.starts_with("pair_init_v1_") && n.ends_with(".json"))
        .filter(|n| !n.starts_with("pair_init_v1_as_v2"))
        .collect();
    names.sort();
    assert!(names.len() >= 7, "PairInit V1 negatives missing: {names:?}");
    for name in names {
        let v = load(&format!("atsam/negative/{name}"));
        let wire = hex_field(&v["input"], "pair_init_wire_hex");
        let err = decode_init(&wire).expect_err(&name);
        assert_eq!(
            format!("{err:?}"),
            v["expected"]["rust_error"].as_str().expect("rust_error"),
            "{name}"
        );
    }
}
